# Generated by Django 2.1.5 on 2019-04-03 00:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('new_snow', models.FloatField(max_length=100, null=True)),
                ('current_weather', models.CharField(max_length=200)),
                ('snowpack', models.FloatField(max_length=100, null=True)),
                ('open_percent', models.FloatField(max_length=100, null=True)),
                ('trails', models.CharField(max_length=100, null=True)),
                ('lifts', models.CharField(max_length=100, null=True)),
                ('base', models.FloatField(max_length=100, null=True)),
                ('conditions', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mountain',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski.State'),
        ),
        migrations.AddField(
            model_name='comments',
            name='mountain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski.Mountain'),
        ),
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
