# Generated by Django 2.1.5 on 2019-04-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='new_snow',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
