# Generated by Django 2.1.5 on 2019-04-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0003_auto_20190403_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='base',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
