# Generated by Django 2.1.5 on 2019-04-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0006_auto_20190403_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski.Mountain')),
            ],
        ),
    ]
