# Generated by Django 2.1.5 on 2019-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0007_geography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='new_snow',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
